name: Docker Image CI for GHCR

on: push
env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/theyeowoon/yeowoon-aws
  DOCKER_CONTAINER: yeowoon-container
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{secrets.GH_ACTOR_NAME}}
          password: ${{secrets.GH_PAT}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_GMAP_API_KEY=${{ secrets.NEXT_PUBLIC_GMAP_API_KEY }}
            NEXT_PUBLIC_YEOWOON_ADDRESS=${{ secrets.NEXT_PUBLIC_YEOWOON_ADDRESS }}
            NEXT_PUBLIC_EMAIL=${{ secrets.NEXT_PUBLIC_EMAIL }}
            NEXT_PUBLIC_EMAIL_PASSWORD=${{ secrets.NEXT_PUBLIC_EMAIL_PASSWORD }}
            NEXT_PUBLIC_CLOUDFRONT_URL=${{ secrets.NEXT_PUBLIC_CLOUDFRONT_URL }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
  deploy:
    needs: [build_and_publish]
    runs-on: [self-hosted]
    steps:
      - name: Login to ghcr
        uses: actions/checkout@v4.2.2
      - name: Setup docker build
        id: buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: login to ghcr
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{secrets.GH_ACTOR_NAME}}
          password: ${{secrets.GH_PAT}}
      - name: Cleanup old images
        run: |
          echo "Starting Docker cleanup..."
          docker images ghcr.io/theyeowoon/yeowoon-aws --format "{{.CreatedAt}}\t{{.ID}}" | \
          sort -r | \
          tail -n +4 | \
          cut -f2 | \
          xargs docker rmi || true
          docker image prune -f
      - name: Run docker
        run: |
          docker stop ${{ env.DOCKER_CONTAINER }} && docker rm ${{ env.DOCKER_CONTAINER }}
          docker run -d -p 3000:3000 --name ${{ env.DOCKER_CONTAINER }} --restart always ${{needs.build_and_publish.outputs.tags}}
